-- user
ALTER TABLE `user`
  COMMENT = '微信用户基本信息',
  MODIFY COLUMN `id`         BIGINT       NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  MODIFY COLUMN `openid`     VARCHAR(64)  NOT NULL COMMENT '微信OpenID，唯一标识',
  MODIFY COLUMN `nickname`   VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '微信昵称',
  MODIFY COLUMN `avatar_url` VARCHAR(512) NOT NULL DEFAULT '' COMMENT '微信头像URL',
  MODIFY COLUMN `phone`      VARCHAR(20)           DEFAULT NULL COMMENT '手机号',
  MODIFY COLUMN `created_at` DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '注册时间';

-- team
ALTER TABLE `team`
  COMMENT = '球队信息',
  MODIFY COLUMN `id`          BIGINT       NOT NULL AUTO_INCREMENT COMMENT '球队ID',
  MODIFY COLUMN `name`        VARCHAR(64)  NOT NULL COMMENT '球队名称',
  MODIFY COLUMN `logo_url`    VARCHAR(512) NOT NULL DEFAULT '' COMMENT '球队Logo URL',
  MODIFY COLUMN `description` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '球队简介',
  MODIFY COLUMN `invite_code` VARCHAR(16)  NOT NULL COMMENT '邀请码，新成员凭此加入',
  MODIFY COLUMN `created_at`  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

-- team_member
ALTER TABLE `team_member`
  COMMENT = '球队成员关系',
  MODIFY COLUMN `id`        BIGINT      NOT NULL AUTO_INCREMENT COMMENT '记录ID',
  MODIFY COLUMN `team_id`   BIGINT      NOT NULL COMMENT '球队ID',
  MODIFY COLUMN `user_id`   BIGINT      NOT NULL COMMENT '用户ID',
  MODIFY COLUMN `role`      VARCHAR(16) NOT NULL DEFAULT 'PLAYER' COMMENT '角色：CAPTAIN/ADMIN/PLAYER',
  MODIFY COLUMN `status`    VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT '状态：PENDING待审/ACTIVE正式/REMOVED已移除',
  MODIFY COLUMN `joined_at` DATETIME             DEFAULT NULL COMMENT '正式入队时间';

-- activity
ALTER TABLE `activity`
  COMMENT = '球队活动（比赛或训练）',
  MODIFY COLUMN `id`          BIGINT       NOT NULL AUTO_INCREMENT COMMENT '活动ID',
  MODIFY COLUMN `team_id`     BIGINT       NOT NULL COMMENT '所属球队ID',
  MODIFY COLUMN `type`        VARCHAR(16)  NOT NULL COMMENT '活动类型：MATCH比赛/TRAINING训练',
  MODIFY COLUMN `title`       VARCHAR(128) NOT NULL COMMENT '活动标题',
  MODIFY COLUMN `opponent`    VARCHAR(64)           DEFAULT NULL COMMENT '对手球队名称（仅比赛）',
  MODIFY COLUMN `location`    VARCHAR(128) NOT NULL DEFAULT '' COMMENT '活动地点',
  MODIFY COLUMN `start_time`  DATETIME     NOT NULL COMMENT '开始时间',
  MODIFY COLUMN `deadline`    DATETIME              DEFAULT NULL COMMENT '报名截止时间，NULL表示不限',
  MODIFY COLUMN `max_players` INT                   DEFAULT NULL COMMENT '最大报名人数，NULL表示不限',
  MODIFY COLUMN `status`      VARCHAR(16)  NOT NULL DEFAULT 'OPEN' COMMENT '状态：OPEN报名中/CLOSED已截止/FINISHED已结束',
  MODIFY COLUMN `created_by`  BIGINT       NOT NULL COMMENT '创建人用户ID',
  MODIFY COLUMN `created_at`  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

-- activity_registration
ALTER TABLE `activity_registration`
  COMMENT = '活动报名记录',
  MODIFY COLUMN `id`          BIGINT      NOT NULL AUTO_INCREMENT COMMENT '报名记录ID',
  MODIFY COLUMN `activity_id` BIGINT      NOT NULL COMMENT '活动ID',
  MODIFY COLUMN `user_id`     BIGINT      NOT NULL COMMENT '报名用户ID',
  MODIFY COLUMN `status`      VARCHAR(16) NOT NULL DEFAULT 'JOINED' COMMENT '报名状态：JOINED已报名/CANCELLED已取消',
  MODIFY COLUMN `created_at`  DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '报名时间';

-- match_result
ALTER TABLE `match_result`
  COMMENT = '比赛结果',
  MODIFY COLUMN `id`          BIGINT       NOT NULL AUTO_INCREMENT COMMENT '结果ID',
  MODIFY COLUMN `activity_id` BIGINT       NOT NULL COMMENT '对应活动ID，唯一',
  MODIFY COLUMN `our_score`   INT          NOT NULL DEFAULT 0 COMMENT '我方得分',
  MODIFY COLUMN `opp_score`   INT          NOT NULL DEFAULT 0 COMMENT '对方得分',
  MODIFY COLUMN `outcome`     VARCHAR(8)   NOT NULL COMMENT '比赛结果：WIN胜/DRAW平/LOSE负',
  MODIFY COLUMN `notes`       VARCHAR(255)          DEFAULT NULL COMMENT '备注',
  MODIFY COLUMN `created_at`  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '录入时间';

-- finance_record
ALTER TABLE `finance_record`
  COMMENT = '球队财务流水记录',
  MODIFY COLUMN `id`          BIGINT        NOT NULL AUTO_INCREMENT COMMENT '记录ID',
  MODIFY COLUMN `team_id`     BIGINT        NOT NULL COMMENT '球队ID',
  MODIFY COLUMN `type`        VARCHAR(16)   NOT NULL COMMENT '收支类型：INCOME收入/EXPENSE支出',
  MODIFY COLUMN `amount`      DECIMAL(10,2) NOT NULL COMMENT '金额（元）',
  MODIFY COLUMN `category`    VARCHAR(32)   NOT NULL COMMENT '分类，如：会费/装备/场地',
  MODIFY COLUMN `description` VARCHAR(255)  NOT NULL DEFAULT '' COMMENT '详细描述',
  MODIFY COLUMN `record_date` DATE          NOT NULL COMMENT '记录日期',
  MODIFY COLUMN `created_by`  BIGINT        NOT NULL COMMENT '创建人用户ID',
  MODIFY COLUMN `created_at`  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

-- member_fee
ALTER TABLE `member_fee`
  COMMENT = '成员会费记录（按赛季）',
  MODIFY COLUMN `id`          BIGINT        NOT NULL AUTO_INCREMENT COMMENT '记录ID',
  MODIFY COLUMN `team_id`     BIGINT        NOT NULL COMMENT '球队ID',
  MODIFY COLUMN `user_id`     BIGINT        NOT NULL COMMENT '成员用户ID',
  MODIFY COLUMN `season`      SMALLINT      NOT NULL COMMENT '赛季年份，如2026',
  MODIFY COLUMN `amount_due`  DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT '应缴会费金额（元）',
  MODIFY COLUMN `amount_paid` DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT '已缴会费金额（元）',
  MODIFY COLUMN `is_paid`     TINYINT(1)    NOT NULL DEFAULT 0 COMMENT '是否已缴清：0否/1是',
  MODIFY COLUMN `updated_at`  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间';
