export default defineAppConfig({
  pages: [
    'pages/home/index',
    'pages/login/index',
    'pages/team-select/index',
    'pages/onboard/index',
    'pages/create-team/index',
    'pages/join-team/index',
    'pages/activity-detail/index',
    'pages/activity-create/index',
    'pages/members/index',
    'pages/finance/index',
    'pages/finance-record/index',
    'pages/member-fee/index',
    'pages/my/index',
    'pages/grouping/index',
    'pages/grouping/poster',
    'pages/activity-poster/index',
    'pages/team-poster/index',
    'pages/privacy/index',
    'pages/terms/index',
  ],
  tabBar: {
    custom: true,
    color: '#4a5a4a',
    selectedColor: '#22c55e',
    list: [
      { pagePath: 'pages/home/index', text: '首页' },
      { pagePath: 'pages/members/index', text: '队员' },
      { pagePath: 'pages/finance/index', text: '财务' },
      { pagePath: 'pages/my/index', text: '我的' },
    ],
  },
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#0f1010',
    navigationBarTitleText: '足球队',
    navigationBarTextStyle: 'white',
  },
})
